name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag mc-status:latest
        docker tag mc-status:latest docker.io/shaandev/mc-status:latest

    - name: Push Docker image to Docker Hub
      run: docker push docker.io/shaandev/mc-status:latest


